### ISSUE TITLE
CSS overlapping definitions

### ISSUE THREAD

**Issue by SreenikethanI** [mtcbpdcdubai/mtcbpdcdubai.github.io#5]
It is noticed that all CSS files are loaded simultaneously, since it's technically a single page app with just one of the "pages" visible at a given moment. Go through all CSS files to ensure that no declarations overlap.

**Comment by SreenikethanI** [comment]
w.r.t. #2, apparently CSS variables cannot be used in media query 😔

I wish something like this would've been possible:
```css
:root {
  --breakpoint: 750px;
}
/* ... */
@media screen and (max-width: var(--breakpoint)) {
  /* ... */
}
```

Here's an explanation: https://stackoverflow.com/questions/40722882
